AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for a Multi-Tenant FastAPI application with Cognito.

Parameters:
  EnvironmentName:
    Type: String
    Default: "dev"
    Description: "Environment name for the deployment"

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: multi-tenant-app-user-pool
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: tenant_id
          AttributeDataType: String
          Mutable: true
          Required: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: multi-tenant-app-user-pool-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
      SupportedIdentityProviders:
        - COGNITO

  CognitoUserPoolGroupAdmin:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: ADMIN
      UserPoolId: !Ref CognitoUserPool
      Description: Tenant admin group for platform

  CognitoUserPoolGroupEditor:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: EDITOR
      UserPoolId: !Ref CognitoUserPool
      Description: Tenant editor group for platform

  CognitoUserPoolGroupViewer:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: VIEWER
      UserPoolId: !Ref CognitoUserPool
      Description: Tenant viewer group for platform
